### ISSUE TITLE
How to create a tab with close button?

### ISSUE THREAD

**Issue by MassMessage** [Zertz/react-headless-tabs#372]
looking for a way to both make tabs with a close button and draggable tabs, I found [this](https://github.com/reactjs/react-tabs/issues/231#issuecomment-689538316) comment pointing to the library. I found it great but couldn't make it work yet. the link to code samples in https://react-headless-tabs.pierluc.io/#examples is broken. Looking around in the repo I found [this](https://github.com/Zertz/react-headless-tabs/blob/main/packages/docs/examples/Browser.tsx) sample (far complex than I though tho)... I couldn't make it work  tho, it seems the css is broken. What am I missing to build this sample work correctly?

**edit 1**: it seems I have to use this library? https://tailwindcss.com/docs/installation it isn't working yet tho, the css isn't working.

**Comment by MassMessage** [comment]
Alright, got it working! to add it to electron, use: https://thoughtbot.com/blog/adding-tailwind-to-electron
if you got the error 

> Error: PostCSS plugin tailwindcss requires PostCSS 8

then you need to use a older version of package, install it like this (source [here](https://stackoverflow.com/a/65058480/800123)):

> Uninstall Tailwind and re-install using the compatibility build instead
> 
> npm uninstall tailwindcss postcss autoprefixer
> npm install tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9

**Comment by Zertz** [comment]
Thanks for pointing out the broken links in examples, I'll fix them shortly!

The concept of closing a tab can be reduced to "remove the tab from the array passed to `useTabs`":

```js
function Example() {
  const [tabs, setTabs] = useState(["one", "two"])

  useTabs(tabs);

  const closeTab = () => {
    // Close tab "two"
    setTabs((tabs) => tabs.filter((tab) => tab !== "two"))
  }
}
```

As for drag and drop, the example uses [react-dnd](https://github.com/react-dnd/react-dnd) but beyond that it depends heavily on your use case and the library you choose.

The examples are made with Tailwind but you can use react-headless-tabs without Tailwind, it is not bound to any styling solution in particular.

**Comment by Zertz** [comment]
> I see. I haven't run this yet but does this include the "X' (close button)? or this is up to me implement it?

The UI is all up to you, this library only handles the logic of maintaining and switching between tabs.
