### ISSUE TITLE
Can I make the tab to mount/unmount when got/lost focus respectively?

### ISSUE THREAD

**Issue by MassMessage** [Zertz/react-headless-tabs#375]
In order to use close/add new tab/drag-and-drop (in the future), I'm porting some code that uses [react-tabs](https://www.npmjs.com/package/react-tabs) to react-headless-tabs. However, I rely on behavior of mount/unmount the tabs panel to mount/unmount the text editors (I'm using monaco). The doc says:

_Depending on the use case, a set of tabs may have different rendering strategies. For the initial render to be as fast as possible, the default tab will always be rendered immediately no matter which strategy is set. **Once mounted, tab panels are hidden but never unmounted.** (emphasis mine)_

So that's preventing the editors to show properly. For performance reasons, I'd like only the current one in use to be mounted. Can I change that behavior in react-headless? I saw render flags and set to always but later on I did realize that didn't work as I expected.

**Comment by Zertz** [comment]
I've never had a need for this this but it did cross my mind a fee times!

We could add an `unmount` prop with similar options as the `render` prop.

**Comment by Zertz** [comment]
I released a new version in which you can do `<TabPanel render="lazy" unmount="always">`, which I think should work for you!

**Comment by MassMessage** [comment]
> I released a new version in which you can do `<TabPanel render="lazy" unmount="always">`, which I think should work for you!

perfect!! it's working fine as expected. Thank you so much such quick feedback and make this work for my case :)
